/*
 * Copyright IBM Corp. 2025
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms provided by IBM in the LICENSE file that accompanied
 * this code, including the "Classpath" Exception described therein.
 */
package ibm.jceplus.junit.base;

import java.io.ByteArrayOutputStream;
import java.security.AlgorithmParameters;
import java.util.Locale;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.PBEParameterSpec;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;

public class BaseTestPBECipher extends BaseTestJunit5 {

    private byte[] ivBytes = {
        0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18,
        0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20,
    };
    private int iterationCount = 300000;
    private byte[] salt = new byte[]{0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08};

    @ParameterizedTest
    @CsvSource({"PBEWithHmacSHA1AndAES_128", "PBEWithHmacSHA1AndAES_256", "PBEWithHmacSHA224AndAES_128", "PBEWithHmacSHA224AndAES_256",
        "PBEWithHmacSHA256AndAES_128", "PBEWithHmacSHA256AndAES_256", "PBEWithHmacSHA384AndAES_128", "PBEWithHmacSHA384AndAES_256",
        "PBEWithHmacSHA512AndAES_128", "PBEWithHmacSHA512AndAES_256", "PBEWithHmacSHA512/224AndAES_128", "PBEWithHmacSHA512/224AndAES_256",
        "PBEWithHmacSHA512/256AndAES_128", "PBEWithHmacSHA512/256AndAES_256", "PBEWithHmacSha1AndAES_128/CBC/PKCS5PAdding",
        "PBEWithHmacSha1AndAES_256/CBC/PKCS5PAdding", "PBEWithHmacSHA224andAES_128/CBC/PkCS5Padding", "PBEWithHmacSHA224andAES_256/CBC/PkCS5Padding",
        "PBEWithHmacSHA256AndAes_128/CBC/PKCS5PaddIng", "PBEWithHmacSHA256AndAes_256/CBC/PKCS5PaddIng", "PBEWithHmacSHa384AndAES_128/CbC/PKCS5Padding",
        "PBEWithHmacSHa384AndAES_256/CbC/PKCS5Padding", "PBEWithHmacSHA512andAES_128/CBc/PKCS5Padding", "PBEWithHmacSHA512andAES_256/CBc/PKCS5Padding",
        "PBEWithHmacSha512/224andAES_128/cBC/PKCS5Padding", "PBEWithHmacSha512/224andAES_256/cBC/PKCS5Padding", "PBEWithHmacShA512/256AndAES_128/CBC/pkCS5Padding",
        "PBEWithHmacShA512/256AndAES_256/CBC/pkCS5Padding"})
    public void testPBE(String algorithm) throws Exception {
        test(algorithm, true);  // salt, ic, IV supplied by the application
        test(algorithm, false); // salt, ic, IV generated by the implementation
    }

    private void test(String algo, boolean suppliedParams)
        throws Exception {

        // Create PBE key
        PBEKeySpec pbeKeySpec = new PBEKeySpec("mypassword".toCharArray());
        int modeIdx = algo.toUpperCase(Locale.ENGLISH).indexOf("/CBC");
        String keyAlgo = (modeIdx == -1 ? algo : algo.substring(0, modeIdx));
        SecretKeyFactory keyFactory = SecretKeyFactory.getInstance(keyAlgo, getProviderName());
        SecretKey pbeKey = keyFactory.generateSecret(pbeKeySpec);

        // Create PBE cipher
        Cipher pbeCipher = Cipher.getInstance(algo, getProviderName());
        Cipher pbeCipherEncrypt = Cipher.getInstance(algo, getProviderName());
        Cipher pbeCipherWrap = Cipher.getInstance(algo, getProviderName());
        Cipher pbeCipherEncryptUpdate = Cipher.getInstance(algo, getProviderName());
        if (suppliedParams) {
            pbeCipher.init(Cipher.ENCRYPT_MODE, pbeKey,
                new PBEParameterSpec(salt, iterationCount,
                    new IvParameterSpec(ivBytes)));
            pbeCipherEncrypt.init(Cipher.ENCRYPT_MODE, pbeKey,
                new PBEParameterSpec(salt, iterationCount,
                    new IvParameterSpec(ivBytes)));
            pbeCipherWrap.init(Cipher.WRAP_MODE, pbeKey,
                new PBEParameterSpec(salt, iterationCount,
                    new IvParameterSpec(ivBytes)));
            pbeCipherEncryptUpdate.init(Cipher.ENCRYPT_MODE, pbeKey,
                new PBEParameterSpec(salt, iterationCount,
                    new IvParameterSpec(ivBytes)));
        } else {
            pbeCipher.init(Cipher.ENCRYPT_MODE, pbeKey);
            pbeCipherEncrypt.init(Cipher.ENCRYPT_MODE, pbeKey);
            pbeCipherWrap.init(Cipher.WRAP_MODE, pbeKey);
            pbeCipherEncryptUpdate.init(Cipher.ENCRYPT_MODE, pbeKey);
        }
        byte[] cleartext = "This is just an example".getBytes();

        // Encrypt
        byte[] ciphertextSame = pbeCipher.doFinal(cleartext);
        byte[] ciphertext = pbeCipherEncrypt.doFinal(cleartext);

        // Wrap
        byte[] wrappedKey = pbeCipherWrap.wrap(pbeKey);

        // Update
        byte[] cipherUpdateText = update(pbeCipherEncryptUpdate, cleartext, 4);

        AlgorithmParameters apsSame = pbeCipher.getParameters();
        AlgorithmParameters aps = pbeCipherEncrypt.getParameters();
        AlgorithmParameters apsWrap = pbeCipherWrap.getParameters();
        AlgorithmParameters apsUpdate = pbeCipherEncryptUpdate.getParameters();

        // Decrypt
        Cipher pbeCipherDecrypt = Cipher.getInstance(algo, getProviderName());
        pbeCipherDecrypt.init(Cipher.DECRYPT_MODE, pbeKey, aps);
        pbeCipher.init(Cipher.DECRYPT_MODE, pbeKey, apsSame);
        byte[] cleartextSame = pbeCipher.doFinal(ciphertextSame);
        byte[] cleartext2 = pbeCipherDecrypt.doFinal(ciphertext);

        // Unwrap
        Cipher pbeCipherUnwrap = Cipher.getInstance(algo, getProviderName());
        pbeCipherUnwrap.init(Cipher.UNWRAP_MODE, pbeKey, apsWrap);
        SecretKey unwrappedKey = (SecretKey) pbeCipherUnwrap.unwrap(wrappedKey, pbeKey.getAlgorithm(), Cipher.SECRET_KEY);

        // Decrypt Update
        Cipher pbeCipherDecryptUpdate = Cipher.getInstance(algo, getProviderName());
        pbeCipherDecryptUpdate.init(Cipher.DECRYPT_MODE, pbeKey, apsUpdate);
        byte[] cleartextUpdate = update(pbeCipherDecryptUpdate, cipherUpdateText, 5);

        assertArrayEquals(cleartext, cleartextSame);
        assertArrayEquals(cleartext, cleartext2);
        assertArrayEquals(pbeKey.getEncoded(), unwrappedKey.getEncoded());
        assertArrayEquals(cleartext, cleartextUpdate);
    }

    private byte[] update(Cipher c, byte[] text, int offset) throws Exception {
        byte[] update1 = c.update(text, 0, offset);
        byte[] update2 = c.update(text, offset, offset);
        byte[] update3 = c.update(text, 2 * offset, text.length - (2 * offset));
        byte[] finalUpdate = c.doFinal();
        ByteArrayOutputStream encryptStream = new ByteArrayOutputStream();
        encryptStream.write(update1);
        encryptStream.write(update2);
        encryptStream.write(update3);
        encryptStream.write(finalUpdate);
        finalUpdate = encryptStream.toByteArray();

        return finalUpdate;
    }
}
