/*
 * Copyright IBM Corp. 2026, 2026
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms provided by IBM in the LICENSE file that accompanied
 * this code, including the "Classpath" Exception described therein.
 */

package ibm.jceplus.junit.base;

import java.security.SecureRandom;
import java.util.Arrays;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

public class BaseTestDRBGCacheBoundary extends BaseTestJunit5 {

    private static final int TEST_CACHE_SIZE_KB = 1;
    private static final int TEST_BYPASS_THRESHOLD_SIZE_KB = 2;

    private static final int TEST_BYTE = TEST_CACHE_SIZE_KB * 1024;
    private static final int TEST_BYPASS_THRESHOLD_BYTES = TEST_BYPASS_THRESHOLD_SIZE_KB * 1024;

    @BeforeAll
    public static void setUp() {
        System.setProperty("openjceplus.randomcachesize",
                String.valueOf(TEST_CACHE_SIZE_KB));
        System.setProperty("openjceplus.randombypassthreshold",
                String.valueOf(TEST_BYPASS_THRESHOLD_SIZE_KB));
    }

    @Test
    public void testDRBG_cacheBoundary_sizeMinusOne() throws Exception {
        SecureRandom sr = SecureRandom.getInstance(getAlgorithm(), getProviderName());

        byte[] bytes = new byte[TEST_BYTE - 1];
        sr.nextBytes(bytes);

        assertEquals(TEST_BYTE - 1, bytes.length, "Unexpected output length");
        assertFalse(allZero(bytes), "Generated bytes should not all be zero");
    }

    @Test
    public void testDRBG_cacheBoundary_size() throws Exception {
        SecureRandom sr = SecureRandom.getInstance(getAlgorithm(), getProviderName());

        byte[] bytes = new byte[TEST_BYTE];
        sr.nextBytes(bytes);

        assertEquals(TEST_BYTE, bytes.length, "Unexpected output length");
        assertFalse(allZero(bytes), "Generated bytes should not all be zero");
    }

    @Test
    public void testDRBG_cacheBoundary_sizePlusOne() throws Exception {
        SecureRandom sr = SecureRandom.getInstance(getAlgorithm(), getProviderName());

        byte[] bytes = new byte[TEST_BYTE + 1];
        sr.nextBytes(bytes);

        assertEquals(TEST_BYTE + 1, bytes.length, "Unexpected output length");
        assertFalse(allZero(bytes), "Generated bytes should not all be zero");
    }

    @Test
    public void testDRBG_cacheBoundary_sequenceAroundBoundary() throws Exception {
        SecureRandom sr = SecureRandom.getInstance(getAlgorithm(), getProviderName());

        // First call leaves 1 byte in cache.
        byte[] first = new byte[TEST_BYTE - 1];
        sr.nextBytes(first);

        // Second call onsumes the last cached byte and force a refill
        // for the remaining byte.
        byte[] second = new byte[2];
        sr.nextBytes(second);

        assertEquals(TEST_BYTE - 1, first.length, "Unexpected first output length");
        assertEquals(2, second.length, "Unexpected second output length");

        assertFalse(allZero(first), "First generated bytes should not all be zero");
        assertFalse(allZero(second), "Second generated bytes should not all be zero");
    }

    @Test
    public void testDRBG_cacheBoundary_outputsDiffer() throws Exception {
        SecureRandom sr = SecureRandom.getInstance(getAlgorithm(), getProviderName());

        byte[] a = new byte[TEST_BYTE];
        byte[] b = new byte[TEST_BYTE];

        sr.nextBytes(a);
        sr.nextBytes(b);

        assertFalse(Arrays.equals(a, b), "Two sequential outputs should not be identical");
    }

    @Test
    public void testDRBG_cacheBoundary_exactDrainThenOneMore() throws Exception {
        SecureRandom sr = SecureRandom.getInstance(getAlgorithm(), getProviderName());

        // Drain exactly one full cache-sized request.
        byte[] first = new byte[TEST_BYTE];
        sr.nextBytes(first);

        // This should require fresh bytes after the exact drain.
        byte[] second = new byte[1];
        sr.nextBytes(second);

        assertEquals(TEST_BYTE, first.length, "Unexpected first output length");
        assertEquals(1, second.length, "Unexpected second output length");

        assertFalse(allZero(first), "First generated bytes should not all be zero");
        assertFalse(allZero(second), "Second generated bytes should not all be zero");
    }

    @Test
    public void testDRBG_cacheBoundary_multiStepCrossing() throws Exception {
        SecureRandom sr = SecureRandom.getInstance(getAlgorithm(), getProviderName());

        // Leave 2 bytes in cache.
        byte[] first = new byte[TEST_BYTE - 2];
        sr.nextBytes(first);

        // Leave 1 byte in cache.
        byte[] second = new byte[1];
        sr.nextBytes(second);

        // Consume the last cached byte and force a refill for the remaining byte.
        byte[] third = new byte[2];
        sr.nextBytes(third);

        assertEquals(TEST_BYTE - 2, first.length, "Unexpected first output length");
        assertEquals(1, second.length, "Unexpected second output length");
        assertEquals(2, third.length, "Unexpected third output length");

        assertFalse(allZero(first), "First generated bytes should not all be zero");
        assertFalse(allZero(second), "Second generated bytes should not all be zero");
        assertFalse(allZero(third), "Third generated bytes should not all be zero");
    }

    @Test
    public void testDRBG_cacheBoundary_repeatedBoundaryRefill() throws Exception {
        SecureRandom sr = SecureRandom.getInstance(getAlgorithm(), getProviderName());

        for (int i = 0; i < 3; i++) {
            byte[] first = new byte[TEST_BYTE - 1];
            sr.nextBytes(first);

            byte[] second = new byte[2];
            sr.nextBytes(second);

            assertEquals(TEST_BYTE - 1, first.length,
                    "Unexpected first output length in iteration " + i);
            assertEquals(2, second.length,
                    "Unexpected second output length in iteration " + i);

            assertFalse(allZero(first),
                    "First generated bytes should not all be zero in iteration " + i);
            assertFalse(allZero(second),
                    "Second generated bytes should not all be zero in iteration " + i);
        }
    }

    @Test
    public void testDRBG_bypassSeparation_largeRequest() throws Exception {
        SecureRandom sr = SecureRandom.getInstance(getAlgorithm(), getProviderName());

        byte[] bytes = new byte[TEST_BYPASS_THRESHOLD_BYTES + 1];
        sr.nextBytes(bytes);

        assertEquals(TEST_BYPASS_THRESHOLD_BYTES + 1, bytes.length, "Unexpected output length");
        assertFalse(allZero(bytes), "Generated bytes should not all be zero");
    }

    private static boolean allZero(byte[] input) {
        for (byte b : input) {
            if (b != 0) {
                return false;
            }
        }
        return true;
    }
}
