/*
 * Copyright IBM Corp. 2026
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms provided by IBM in the LICENSE file that accompanied
 * this code, including the "Classpath" Exception described therein.
 */

package ibm.jceplus.junit.tests;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * Exercises PQC key interoperability between the OCK and OpenSSL backends
 * of the same OpenJCEPlus provider.
 *
 * <p>Two parameter sets are run by {@code BaseTestPQCKeyInterop}:
 * <ol>
 *   <li>{@code (OpenJCEPlus_OCK, OpenJCEPlus_OpenSSL, OpenJCEPlus_OpenSSL)} - keys
 *       generated by the OCK backend are used with an OpenSSL-backed operation.</li>
 *   <li>{@code (OpenJCEPlus_OpenSSL, OpenJCEPlus_OCK, OpenJCEPlus_OCK)} - the reverse
 *       direction.</li>
 * </ol>
 *
 * <p>OpenSSL is not available on z/OS; the factory method returns an empty stream there,
 * so no test cases will be generated on that platform.
 */
@Tag(Tags.OPENJCEPLUS_OCK_NAME)
@Tag(Tags.OPENJCEPLUS_OPENSSL_NAME)
@MethodSource("ibm.jceplus.junit.tests.TestArguments#getOCKAndOpenSSLCrossBackendProviders")
public class TestPQCKeyInteropBackends extends BaseTestPQCKeyInterop {
    // Parameter injection and all test methods are inherited from BaseTestPQCKeyInterop.
}
